## very very simple Rakefile here :)
namespace :test do
task :run do
  system "ruby superhero_test.rb false"
end
task :with_extension do
  system "ruby superhero_test.rb true"
end
end

task test: 'test:run'


